name: First workflow

on:
  push:
   
permissions:
  contents: read

jobs:
  myjob:
    name: Deploying
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configuring AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA2E76B54NNCGRUQNX
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Building image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: example
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker image build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
